### ISSUE TITLE
Unable to finish configuration on windows

### ISSUE THREAD

**Issue by AlexBokhankovich** [rahiel/telegram-send#10]
The script throws an error after the bot's password is entered

```
telegram-send is now ready for use!
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\telegram-send.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\telegram_send.py", line 55, in main
    return configure(args.conf, fm_integration=True)
  File "c:\python36\lib\site-packages\telegram_send.py", line 207, in configure
    with open(conf, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alex.bokhankovich\\AppData\\Local\\telegram-send\\telegram-send.conf'
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by rahiel** [comment]
Thanks for reporting this bug. I've just released a new version that should fix this. 
Please upgrade with
```
pip3 install telegram-send --upgrade
```
(Or just add the `--upgrade` option to whatever install command you used.)

**Comment by AlexBokhankovich** [comment]
Thank you for the update. It almost solved the issue. Currently the script finished configuring but it throws an error at the end of the configuration process but it works just fine despite of the error

Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\telegram-send.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\telegram_send.py", line 55, in main
    return configure(args.conf, fm_integration=True)
  File "c:\python36\lib\site-packages\telegram_send.py", line 211, in configure
    return integrate_file_manager()
  File "c:\python36\lib\site-packages\telegram_send.py", line 240, in integrate_file_manager
    if which(fm):
  File "c:\python36\lib\site-packages\telegram_send.py", line 256, in which
    return check_output(["which", p]).decode("utf-8").strip().endswith(p)
  File "c:\python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]

**Comment by rahiel** [comment]
I released another version that should fix this. Thanks for testing on Windows.

**Comment by rahiel** [comment]
I released another version that should fix this. Thanks for testing on Windows.

**Comment by AlexBokhankovich** [comment]
Work like a charm. Thank you.
