### ISSUE TITLE
Latest 0.28.1 returns error for send: chat_id.isdigit() not a string

### ISSUE THREAD

**Issue by rausb** [rahiel/telegram-send#100]
Hi there,

latest version 0.28.1 returns for this simple test program:
**import telegram_send
telegram_send.send(messages=["Hello!"])**

the error:
_Traceback (most recent call last):
  File "c:\users\ich\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ich\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ich\AppData\Local\Programs\Python\Python39\Scripts\telegram-send.exe\__main__.py", line 7, in <module>
  File "c:\users\ich\appdata\local\programs\python\python39\lib\site-packages\telegram_send\telegram_send.py", line 131, in main
    delete(args.delete)
  File "c:\users\ich\appdata\local\programs\python\python39\lib\site-packages\telegram_send\telegram_send.py", line 330, in delete
    settings = get_config_settings(conf)
  File "c:\users\ich\appdata\local\programs\python\python39\lib\site-packages\telegram_send\telegram_send.py", line 531, in get_config_settings
    chat_id = int(chat_id) if chat_id.isdigit() else chat_id
AttributeError: 'int' object has no attribute 'isdigit'_

**Comment by rausb** [comment]
it has been fixed in 0.29, thanks

**Comment by rahiel** [comment]
Hey this was an error in a very recent refactor, it should be fixed in the current version!
