### ISSUE TITLE
Filesize limit and streamable videos

### ISSUE THREAD

**Issue by Alex-Laparra** [rahiel/telegram-send#104]
Are you planning on making it possible to send files larger than 50mb (as telegram allows up to 2gb)?
Videos sent through this api are not streamable inside telegram, you have to download them entirely before watching them, are planning on implementing streamable videos upload?

**Comment by rahiel** [comment]
I just released version 0.34 which sends streaming videos by default now 😁

Telegram-send supports the filesize limit of telegram, it doesn't check it itself, so just try uploading larger files!

Implemented in https://github.com/rahiel/telegram-send/commit/34d7703754d441a6f4c4a7b5b3210759d36078e2

**Comment by Alex-Laparra** [comment]
When I try to upload files larger than let's say 50 mb, i get this error 15 seconds in:

```

```

**Comment by Alex-Laparra** [comment]
I also get this
````
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "[redacted].py", line 10, in <module>
    telegram_send.send(videos=[f], conf="[redacted]", captions=[lam[:-4]],timeout=60000)
  File "C:\Python310\lib\site-packages\telegram_send\telegram_send.py", line 288, in send
    message_ids += [bot.send_video(video=v, caption=c, supports_streaming=True, **kwargs_caption)]
  File "C:\Python310\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\telegram\bot.py", line 1177, in send_video
    return self._message(  # type: ignore[return-value]
  File "C:\Python310\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Python310\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Python310\lib\site-packages\telegram\utils\request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "C:\Python310\lib\site-packages\telegram\utils\request.py", line 285, in _request_wrapper
    raise NetworkError(
telegram.error.NetworkError: File too large. Check telegram api limits https://core.telegram.org/bots/api#senddocument
````

**Comment by rahiel** [comment]
In the docs I read from the error message (telegram.error.NetworkError: File too large. Check telegram api limits https://core.telegram.org/bots/api#senddocument)

> Bots can currently send video files of up to 50 MB in size, this limit may be changed in the future.

So the file limit of 50MB is still in place.
