### ISSUE TITLE
Bot added to the group doesn't receive messages

### ISSUE THREAD

**Issue by neooleg** [rahiel/telegram-send#11]
Hi,

bot added to the group doesn't show messages send to it. However, personally it shows, but _only for the first recipient_.

P.S. /setprivacy disabled just in case.

**Comment by rahiel** [comment]
Hello!

I haven't added support for groups yet, I'll look at it soon-ish.

**Comment by rahiel** [comment]
@neooleg I've released a new version with group support, could you upgrade and test it out with `telegram-send --configure-group`?

(You can upgrade by adding the `--upgrade` option to the pip command you've used to install telegram-send)

**Comment by neooleg** [comment]
Hi @rahiel,

thanks for quick response!

It rises error. There is report after invoke `telegram-send --configure-group`
```
Error! 'NoneType' object has no attribute 'strip'
Error! 'NoneType' object has no attribute 'strip'
Error! 'NoneType' object has no attribute 'strip'
................
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/connectionpool.py", line 395, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 60, in main
    return configure(args.conf, group=True)
  File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 204, in configure
    update, update_id = get_user()
  File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 193, in get_user
    updates = bot.get_updates(offset=update_id, timeout=10)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 1387, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 246, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 168, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/telegram/vendor/urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1208, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 380, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 342, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 769, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 641, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
```

**Comment by rahiel** [comment]
I've now released a fix for that, could you upgrade and try again?

**Comment by neooleg** [comment]
Now it works as expected, thanks a lot!

**Comment by AtomicNess123** [comment]
I'm getting this "'NoneType' object has no attribute 'group" when creating a channel group. Any ideas?
