### ISSUE TITLE
telegram.error.BadRequest: Image_process_failed

### ISSUE THREAD

**Issue by yermulnik** [rahiel/telegram-send#134]
Failing to send image 🙁
```shell
> telegram-send --version
telegram-send 0.37

> telegram-send -g --image zzz.png
Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram_send/telegram_send.py", line 49, in main
    asyncio.run(run())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram_send/telegram_send.py", line 164, in run
    raise(e)
  File "/usr/local/lib/python3.12/dist-packages/telegram_send/telegram_send.py", line 130, in run
    message_ids += await send(
                   ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram_send/telegram_send.py", line 276, in send
    message_ids += [await bot.send_photo(photo=i, **kwargs)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/_bot.py", line 1075, in send_photo
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/_bot.py", line 697, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/telegram/request/_baserequest.py", line 325, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Image_process_failed
```

**Comment by yermulnik** [comment]
Tried another similar tool and it failed with the same diags: `400: Bad Request: IMAGE_PROCESS_FAILED` — seems line not a `telegram-send` issue. Closing.

**Comment by yermulnik** [comment]
OMG, I was trying to send non-image file 🤦🏻
