### ISSUE TITLE
Trying to install on a server without root access

### ISSUE THREAD

**Issue by Qwerty-Space** [rahiel/telegram-send#21]
Hello, I have a server without root access, and python is installed to ~/python.

How can I get this to work?

I tried changing this to various things, but I either get `bad interpreter:  No such file or directory` or `bad interpreter: Permission denied`
![image](https://user-images.githubusercontent.com/6967592/29532495-67534c5c-86a5-11e7-9ec5-d734ac3d02be.png)

Thanks

**Comment by rahiel** [comment]
Did you install Python 3 in your home directory? Then you can try `python3 -m pip install telegram-send` where python3 is the python executable in your `~`. This would install the telegram-send executable in `~/.local/bin`, so add that directory to your path. (See [this guide](https://www.cpu.re/installing-programs-from-non-system-package-managers-without-sudo/) if you need help with that.)

**Comment by Qwerty-Space** [comment]
Thanks, it installed correctly, but I have this problem

```[zeus ~] ~/python/Python-3.5.0/python -m pip install telegram-send
Collecting telegram-send
  Downloading telegram_send-0.13-py2.py3-none-any.whl
Collecting appdirs (from telegram-send)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting colorama (from telegram-send)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting python-telegram-bot>=5.0 (from telegram-send)
  Downloading python_telegram_bot-7.0.1-py2.py3-none-any.whl (290kB)
    100% |████████████████████████████████| 296kB 3.3MB/s
Collecting certifi (from python-telegram-bot>=5.0->telegram-send)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 2.8MB/s
Collecting future>=0.16.0 (from python-telegram-bot>=5.0->telegram-send)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.3MB/s
Installing collected packages: appdirs, colorama, certifi, future, python-telegram-bot, telegram-send
  Running setup.py install for future ... done
Successfully installed appdirs-1.4.3 certifi-2017.7.27.1 colorama-0.3.9 future-0.16.0 python-telegram-bot-7.0.1 telegram-send-0.13
[zeus ~] telegram-send
-bash: telegram-send: command not found
```

**Comment by Qwerty-Space** [comment]
Oh I'm dumb

**Comment by Qwerty-Space** [comment]
[zeus ~/.local/bin] ls
pip   pip2.7         pyrsa-decrypt-bigfile  pyrsa-encrypt-bigfile  pyrsa-priv2pub  pyrsa-verify
pip2  pyrsa-decrypt  pyrsa-encrypt          pyrsa-keygen           pyrsa-sign
[zeus ~/.local/bin]

**Comment by rahiel** [comment]
The executable should be somewhere, in `~` run: `find . -iname *telegram-send*`, that should find where pip installed it.

**Comment by Qwerty-Space** [comment]
It's in `~/python/python3/bin`

**Comment by Qwerty-Space** [comment]
I added that directory to path.  But I get this error when sending a file:
```
[zeus ~] telegram-send -f private/rtorrent/data/ab/Kakegurui/\[Hiryuu\]\ Kakegurui\ -\ 01v2\ \[1080p\ H264\ AC3\]\[E101C0F1\].mkv --timeout 1000
Traceback (most recent call last):
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/utils/request.py", line 134, in _parse
    data = json.loads(decoded_s)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sdh1/home/qwertyspace/python/python3/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram_send.py", line 97, in main
    timeout=args.timeout
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram_send.py", line 173, in send
    bot.send_document(chat_id=chat_id, document=f)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/bot.py", line 69, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/bot.py", line 175, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/utils/request.py", line 248, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/utils/request.py", line 187, in _request_wrapper
    message = self._parse(resp.data)
  File "/media/sdh1/home/qwertyspace/python/python3/lib/python3.5/site-packages/telegram/utils/request.py", line 136, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response
```

**Comment by rahiel** [comment]
Is that file bigger than 50 MB? Telegram doesn't support sending files larger than that.

**Comment by Qwerty-Space** [comment]
Telegram does support sending files as large as 1GB.  I have a channel with ~500MB sized files

![image](https://user-images.githubusercontent.com/6967592/29577724-6c7f9a72-8764-11e7-8dda-2901960c4f46.png)

**Comment by Qwerty-Space** [comment]
Oh, you mean bots?
Damn

**Comment by rahiel** [comment]
Yes, telegram-send uses the Bot API and the limit is currently [50 MB](https://core.telegram.org/bots/api#senddocument).

**Comment by rahiel** [comment]
For future visitors: if you have pip/pip3 installed on your system you can simply `pip3 install telegram-send` without sudo, this places the binary in `~/.local/bin`.
