### ISSUE TITLE
Fails when markdown/html syntax is not 100% correct

### ISSUE THREAD

**Issue by ndemou** [rahiel/telegram-send#27]
Hi and thanks for telegram-send. I noticed that when I use makdown or html formats telegram-send will fail to send the message and raise an error if the syntax is not 100% correct like in these example:
```
$ telegram-send --format markdown "another *test"
Traceback (most recent call last):
  ...
telegram.error.BadRequest: Can't parse entities in message text: can't find end of the entity starting at byte offset 20

$ telegram-send --format html "another <b>test"
Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 127, in main
    raise(e)
  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 111, in main
    timeout=args.timeout
  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 185, in send
    bot.send_message(chat_id=chat_id, text=m, parse_mode=parse_mode)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 82, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 210, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities in message text: can't found end tag corresponding to start tag at byte offset 8

```

**Comment by rahiel** [comment]
Yes you can only send correct markdown/html.

**Comment by ndemou** [comment]
Hi Rahiel, this is in fact a bug report and not a question. I'm sorry I can't offer a patch.

**Comment by rahiel** [comment]
@ndemou There's nothing that telegram-send can do about this, the [Telegram Bot API](https://core.telegram.org/bots/api) only accepts valid markdown/HTML. The user should take care to send valid HTML/Markdown.
