### ISSUE TITLE
Python2.7 ConfigParser has no attribute '__setitem__'

### ISSUE THREAD

**Issue by sethwoodworth** [rahiel/telegram-send#3]
When using Python2.7
```
ERROR: Failed to send notification using telegram
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntfy/__init__.py", line 48, in notify
    **backend_config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/telegram.py", line 17, in notify
    configure(config_file)
  File "/usr/local/lib/python2.7/dist-packages/telegram_send.py", line 185, in configure
    config["telegram"] = {"TOKEN": token, "chat_id": chat_id}
AttributeError: ConfigParser instance has no attribute '__setitem__'

```
```python
config = configparser.ConfigParser()
config['telegram'] = {"TOKEN": token, "chat_id": chat_id}
```

This appears to be a difference between py2 and py3 `ConfigParser` apis.

**Comment by rahiel** [comment]
Thanks for reporting this bug! I've just fixed compatibility with Python 2.7
Please update with:
```
pip install telegram-send --upgrade
```
