### ISSUE TITLE
Not working with socks5 proxy with auth - doesn't pass credentials

### ISSUE THREAD

**Issue by k1tzu** [rahiel/telegram-send#31]
```
#export https_proxy=socks5://user:pass@IP:PORT
#telegram-send "hello"
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/socks.py", line 851, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/lib/python3.6/site-packages/socks.py", line 497, in _negotiate_SOCKS5
    self, CONNECT, dest_addr)
  File "/usr/lib/python3.6/site-packages/socks.py", line 578, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/contrib/socks.py", line 87, in _new_conn
    **extra_kw
  File "/usr/lib/python3.6/site-packages/socks.py", line 262, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/socks.py", line 252, in create_connection
    sock.connect((remote_host, remote_port))
  File "/usr/lib/python3.6/site-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/socks.py", line 855, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/contrib/socks.py", line 109, in _new_conn
    "Failed to establish a new connection: %s" % error
telegram.vendor.ptb_urllib3.urllib3.exceptions.NewConnectionError: <telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7faeb4db38>: Failed to establish a new connection: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 195, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError:  NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7faeb4db38>: Failed to establish a new connection: 0x04: Host unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/telegram_send.py", line 132, in main
    raise(e)
  File "/usr/lib/python3.6/site-packages/telegram_send.py", line 116, in main
    timeout=args.timeout
  File "/usr/lib/python3.6/site-packages/telegram_send.py", line 202, in send
    send_message(m)
  File "/usr/lib/python3.6/site-packages/telegram_send.py", line 191, in send_message
    return bot.send_message(chat_id=chat_id, text=message, parse_mode=parse_mode, disable_web_page_preview=disable_web_page_preview)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 278, in post
    **urlopen_kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 201, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
```
Arch Linux 3.14.79+

Other software like pip3 works via socks5 normally.

**Comment by rahiel** [comment]
Thanks for reporting this bug. It's a bug in the upstream [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) dependency. It will be fixed at some later release.

**Comment by k1tzu** [comment]
I was able to dirty-fix it by explicitly adding proxy to telegram.Bot request in telegram-send like this:
```
SOCKS_URL="socks5://127.0.0.1:443
SOCKS_USER="user"
SOCKS_PASS="pass"

request = telegram.utils.request.Request(proxy_url = SOCKS_URL,
                                                                urllib3_proxy_kwargs = {
                                'username': SOCKS_USER,
                                'password': SOCKS_PASS,
       		},
                  				read_timeout=timeout
                                                )
    bot = telegram.Bot(token, request=request)
```

**Comment by rahiel** [comment]
Whoever would like to see this fixed, please vote (click the "thumbs up" icon on the first comment) for this upstream issue: https://github.com/python-telegram-bot/python-telegram-bot/issues/1087.

**Comment by rahiel** [comment]
This is fixed in https://github.com/rahiel/telegram-send/commit/c0a56f125842d4f7485df691bd226b378018a3ee and will be in the next release.
