### ISSUE TITLE
Configuration Error while entering API Key

### ISSUE THREAD

**Issue by rakshith95** [rahiel/telegram-send#61]
When I try `telegram-send --configure`, It gives the following prompt, to which I enter the key generated from the BotFather:
```
Talk with the BotFather on Telegram (https://telegram.me/BotFather), create a bot and insert the token
❯ Number:Key
```
However. I get the following error messages:

> Something went wrong, please try again.

```

Traceback (most recent call last):
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botNumber:Key/getMe (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rakshith/anaconda3/envs/detect_cv/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/home/rakshith/anaconda3/envs/detect_cv/lib/python3.6/site-packages/telegram_send.py", line 83, in main
    return configure(conf[0], fm_integration=True)
  File "/home/rakshith/anaconda3/envs/detect_cv/lib/python3.6/site-packages/telegram_send.py", line 308, in configure
    return configure()
TypeError: configure() missing 1 required positional argument: 'conf'
```
This happens on one system, even if I create new bots, and keys, and try.

**Comment by eightlay** [comment]
Have the same issue
Did you solve it?

**Comment by rahiel** [comment]
This bug should be fixed in the latest version, please upgrade and try again.
