### ISSUE TITLE
Missing attributes of telegram module

### ISSUE THREAD

**Issue by exander77** [rahiel/telegram-send#62]
I started getting this weird error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telegram_send.py", line 127, in main
    timeout=args.timeout
  File "/usr/local/lib/python3.7/dist-packages/telegram_send.py", line 195, in send
    request = telegram.utils.request.Request(read_timeout=timeout)
AttributeError: module 'telegram' has no attribute 'utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/telegram_send.py", line 136, in main
    except telegram.error.NetworkError as e:
AttributeError: module 'telegram' has no attribute 'error'
```

**Comment by rahiel** [comment]
1. Make sure your own python script is not named `telegram.py` as that causes a conflict with the telegram bot API library that we use.
2. You might have a conflict with a different module that is also using the `telegram` name, this package depends on the https://github.com/python-telegram-bot/python-telegram-bot library that ships with the `telegram.constants` module. Try again in a fresh virtualenv.

You might also like to install it using pipx: https://pypa.github.io/pipx/
Then: `pipx install telegram-send`
