### ISSUE TITLE
ImportError: No module named html

### ISSUE THREAD

**Issue by yuki-uthman** [rahiel/telegram-send#72]
The package got installed without any errors but when I try to run it it says this.

telegram-send
Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 5, in <module>
    from telegram_send import main
  File "/Library/Python/2.7/site-packages/telegram_send.py", line 28, in <module>
    import telegram
  File "/Users/Yuki/Library/Python/2.7/lib/python/site-packages/telegram/__init__.py", line 23, in <module>
    from .user import User
  File "/Users/Yuki/Library/Python/2.7/lib/python/site-packages/telegram/user.py", line 23, in <module>
    from telegram.utils.helpers import mention_html as util_mention_html
  File "/Users/Yuki/Library/Python/2.7/lib/python/site-packages/telegram/utils/helpers.py", line 26, in <module>
    from html import escape
ImportError: No module named html

**Comment by rahiel** [comment]
Python 2.7 is not supported, please use Python 3.6+
