### ISSUE TITLE
markup error

### ISSUE THREAD

**Issue by kiselev-dv** [rahiel/telegram-send#8]
Hi got an error: looks like something went wrong with coloring.

```
Talk with the BotFather on Telegram (https://telegram.me/BotFather), create a bot and insert the token
Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 56, in main
    return configure(args.conf, fm_integration=True)
  File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 137, in configure
    token = input(markup(prompt, "magenta")).strip()
UnicodeEncodeError: 'ascii' codec can't encode character '\u276f' in position 5: ordinal not in range(128)
```

**Comment by rahiel** [comment]
Hi @kiselev-dv, it sounds like your terminal cannot display unicode. Can you check if your terminal's encoding is set to UTF-8? If that doesn't help, I've just released a new version with a workaround.
Update with:
```shell
sudo pip3 install telegram-send --upgrade
```

**Comment by kiselev-dv** [comment]
Seems so, my $LANG and $LC_CTYPE are empty, so it most probbably my env misconfiguration. 
Anyway your workaround helps, thanks.
