### ISSUE TITLE
Sending large amount of data into as stdin throwing error "Can't parse entities: can't find end of the entity starting at byte offset 0"

### ISSUE THREAD

**Issue by ns-busker** [rahiel/telegram-send#80]
### Sending big chunk of message(subdomains) as stdin using following command and getting following error
cat 1000subs.txt | telegram-send --pre --stdin

/usr/local/lib/python3.8/dist-packages/telegram_send.py:211: UserWarning: Message longer than MAX_MESSAGE_LENGTH=4096, splitting into smaller messages.
  warn(markup("Message longer than MAX_MESSAGE_LENGTH=%d, splitting into smaller messages." % MAX_MESSAGE_LENGTH, "red"))
Traceback (most recent call last):                                                          
  File "/usr/local/bin/telegram-send", line 8, in <module>                                                                                                                               
    sys.exit(main())                          
  File "/usr/local/lib/python3.8/dist-packages/telegram_send.py", line 107, in main                                                                                                      
    send(messages=[message], conf=c, parse_mode=args.parse_mode, silent=args.silent, disable_web_page_preview=args.disable_web_page_preview)
  File "/usr/local/lib/python3.8/dist-packages/telegram_send.py", line 214, in send                                                                                                      
    send_message(m)                           
  File "/usr/local/lib/python3.8/dist-packages/telegram_send.py", line 207, in send_message                                                                                              
    return bot.send_message(chat_id=chat_id, text=message, parse_mode=parse_mode, disable_notification=silent, disable_web_page_preview=disable_web_page_preview)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 126, in decorator                                                                                                  
    result = func(*args, **kwargs)                                                          
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 474, in send_message                                                                                               
    return self._message(  # type: ignore[return-value]                                                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 295, in _message                                                                                                   
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 258, in _post                                                                                                      
    return self.request.post(                 
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 349, in post                                                                                             
    result = self._request_wrapper(                                                         
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise BadRequest(message)                 
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 0

**Comment by rahiel** [comment]
There was a bug when using the pre and stdin options together with very long messages, this is fixed now in the latest version.

Thanks for reporting!
