### ISSUE TITLE
socket.gaierror: [Errno 11002] getaddrinfo failed when trying to configure telegram-send

### ISSUE THREAD

**Issue by chipijui** [rahiel/telegram-send#87]
Hello, I am behind a proxy.pac. I'm trying to configure telegram-send in windows 10 / Python 3.9.5
Should I indicate a certificate?
If yes, how must I perform it?

thanks in advance!

C:\>telegram-send --configure
Talk with the BotFather on Telegram (https://telegram.me/BotFather), create a bot and insert the token
[35m> [0mxxxxxxxxxxxxxx
 Something went wrong, please try again.

Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 140, in _new_conn
    conn = connection.create_connection(
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\python\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 149, in _new_conn
    raise NewConnectionError(
telegram.vendor.ptb_urllib3.urllib3.exceptions.NewConnectionError: <telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF4AA8D9D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\telegram\utils\request.py", line 253, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "c:\python\python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1707966557:AAFomBY8-smOfj411XyUOxhmUvauEJCmn5k/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF4AA8D9D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\telegram_send.py", line 305, in configure
    bot_name = bot.get_me().username
  File "c:\python\python39\lib\site-packages\telegram\bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "c:\python\python39\lib\site-packages\telegram\bot.py", line 408, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "c:\python\python39\lib\site-packages\telegram\bot.py", line 259, in _post
    return self.request.post(
  File "c:\python\python39\lib\site-packages\telegram\utils\request.py", line 350, in post
    result = self._request_wrapper(
  File "c:\python\python39\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1707966557:AAFomBY8-smOfj411XyUOxhmUvauEJCmn5k/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF4AA8D9D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python39\Scripts\telegram-send.exe\__main__.py", line 7, in <module>
  File "c:\python\python39\lib\site-packages\telegram_send.py", line 83, in main
    return configure(conf[0], fm_integration=True)
  File "c:\python\python39\lib\site-packages\telegram_send.py", line 308, in configure
    return configure()
TypeError: configure() missing 1 required positional argument: 'conf'

**Comment by shuivin** [comment]
same issue .

**Comment by shuivin** [comment]
i found the resolution.
for example, my bot api as blew.
```
https://api.telegram.org/bot718834189:AAH3eqlmKHWcAU7LIiAhcW6duGnoH4LmY/sendMessage
```
in telegram-send config.
we need to use `718834189:AAH3eqlmKHWcAU7LIiAhcW6duGnoH4LmY`
not
`bot718834189:AAH3eqlmKHWcAU7LIiAhcW6duGnoH4LmY`

**Comment by chipijui** [comment]
Thank you @shuivin for your post!  I use it as you suggested, but I'm getting the same error. I think it could be the proxy.pac, but I was unable to find a solution yet.
Very kind of you! Best regards

**Comment by rahiel** [comment]
Please try again with a clean install of the latest telegram-send, the underlying libraries have also had a lot of updates.

Maybe try using the `HTTPS_PROXY` environment variable? https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy
