### ISSUE TITLE
Send 50Mb file

### ISSUE THREAD

**Issue by trvsk** [rahiel/telegram-send#9]
Hello. 
I try to send file more than 50MB, but have error

```
# truncate -s 50M filename
# telegram-send --file /home/k.turevsky/filename
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 98, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/telegram-send", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/telegram_send.py", line 64, in main
    send(messages=args.message, conf=args.conf, parse_mode=args.parse_mode, files=args.file, images=args.image, captions=args.caption)
  File "/usr/lib/python3.4/site-packages/telegram_send.py", line 110, in send
    bot.sendDocument(chat_id=chat_id, document=f)
  File "/usr/lib/python3.4/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/telegram/bot.py", line 151, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 199, in post
    result = self._request_wrapper('POST', url, body=data.to_form(), headers=data.headers)
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 145, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 100, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response

```

If file 49MB everything OK!

**Comment by rahiel** [comment]
You've discovered Telegram's max file size of 50 MB. You can't send files larger than that. I've added a note to the readme.

**Comment by trvsk** [comment]
Thanks for the answer!
